### ISSUE TITLE
Memento is not redundant if one cassandra fails

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/memento#3]
If a request reaches a memento node with a broken cassandra, processing will fail and we have no way of retrying with a new memento node.

**Comment by rkd-msw** [comment]
Marking all Memento/Gemini/Restund issues as low priority for now.

**Comment by rkd-msw** [comment]
This is fixed by https://github.com/Metaswitch/memento/pull/145 - when that's merged, Memento will be able to connect to a pool of external Cassandras, and retry to a second one if the first one it tries is down.
