### ISSUE TITLE
Manual install instructions are sadly lacking

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/memento#33]
As per title.  Specific issues

-  no mention of need to ensure port 443 is open to world on memento nodes (or sprout nodes if co-resident)
-  no mention of need to set up memento_hostname in /etc/clearwater/config (must be set to memento.sprout.<home domain> if coresident on sprout nodes)
-  no mention of memento-as package.

Should also clarify live test documentation.

**Comment by graemerobertson** [comment]
When this issue gets fixed, we should consider also linking to the Memento HTTPS certificates doc (https://github.com/Metaswitch/memento/blob/dev/docs/HTTPSCertificates.md) as per RKD's comment on closed issue https://github.com/Metaswitch/memento/issues/22

**Comment by eleanor-merry** [comment]
Closing as these have been fixed up in various commits
