### ISSUE TITLE
Memento AuthStore doesn't use CAS when updating records

### ISSUE THREAD

**Issue by mike-evans** [Metaswitch/memento#36]
When the Memento AuthStore object attempts to updating a record it doesn't remember the CAS value when the record was read, so the updates fail.

**Comment by AlexHockey** [comment]
@mike-evans, a few questions on this:

* Can you remember the scenario that caused this? 
* Did you make any progress towards a fix?

**Comment by mike-evans** [comment]
The scenario is where HTTPDigestAuthenticate::retrieve_digest_from_store calls AuthStore::get_digest, which is successful, then calls HTTPDigestAuthenticate::check_if_matches which calls AuthStore::set_digest to update the nonce count, which fails because the underlying store tries to do an ADD for a record which already exists.

I didn't do any work on a fix.  We probably need to store the cas value in the AuthStore::Digest object when the record is read, and use this value when it's written back to the store.

**Comment by AlexHockey** [comment]
I have pushed a fix to the [issue36](https://github.com/Metaswitch/memento/tree/issue36) branch that stores the CAS on the Digest objects read from the store, and uses them on writes back to the store. I haven't yet written any code to recover if the write fails because of a CAS mismatch.
